import type { Theme } from "@/components/ui/theme-provider.js";

export const defaultTheme: Theme = {
  name: "default",
  colors: {
    primary: "cyan",
    primaryForeground: "black",
    secondary: "magenta",
    secondaryForeground: "white",
    accent: "blueBright",
    accentForeground: "white",
    success: "green",
    successForeground: "black",
    warning: "yellow",
    warningForeground: "black",
    error: "red",
    errorForeground: "white",
    info: "cyan",
    infoForeground: "black",
    background: "black",
    foreground: "white",
    muted: "blackBright",
    mutedForeground: "gray",
    border: "gray",
    focusRing: "cyan",
    selection: "cyanBright",
    selectionForeground: "black",
  },
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    bold: true,
    sm: "13",
    base: "14",
    lg: "16",
    xl: "20",
  },
  border: {
    style: "round",
    color: "gray",
    focusColor: "cyan",
  },
};
